// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mq-service.proto

/*
Package mq is a generated protocol buffer package.

It is generated from these files:
	mq-service.proto

It has these top-level messages:
	SystemEvent
	EventPhotoScanUploaded
	EventPhotoScanSampled
	PubPhotoScanUploadedRequest
	PubPhotoScanUploadedResponse
	PubPhotoScanSampledRequest
	PubPhotoScanSampledResponse
*/
package mq

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "gitlab.com/project-leaf/mq-service-go/src/proto/core"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A wrapper struct encapsulating one of any possible event types flowing through the system.
type SystemEvent struct {
	Context *core.Context `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*SystemEvent_PhotoScanUploaded
	//	*SystemEvent_PhotoScanSampled
	Event isSystemEvent_Event `protobuf_oneof:"event"`
}

func (m *SystemEvent) Reset()                    { *m = SystemEvent{} }
func (m *SystemEvent) String() string            { return proto.CompactTextString(m) }
func (*SystemEvent) ProtoMessage()               {}
func (*SystemEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isSystemEvent_Event interface {
	isSystemEvent_Event()
}

type SystemEvent_PhotoScanUploaded struct {
	PhotoScanUploaded *EventPhotoScanUploaded `protobuf:"bytes,2,opt,name=photoScanUploaded,oneof"`
}
type SystemEvent_PhotoScanSampled struct {
	PhotoScanSampled *EventPhotoScanSampled `protobuf:"bytes,3,opt,name=photoScanSampled,oneof"`
}

func (*SystemEvent_PhotoScanUploaded) isSystemEvent_Event() {}
func (*SystemEvent_PhotoScanSampled) isSystemEvent_Event()  {}

func (m *SystemEvent) GetEvent() isSystemEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *SystemEvent) GetContext() *core.Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SystemEvent) GetPhotoScanUploaded() *EventPhotoScanUploaded {
	if x, ok := m.GetEvent().(*SystemEvent_PhotoScanUploaded); ok {
		return x.PhotoScanUploaded
	}
	return nil
}

func (m *SystemEvent) GetPhotoScanSampled() *EventPhotoScanSampled {
	if x, ok := m.GetEvent().(*SystemEvent_PhotoScanSampled); ok {
		return x.PhotoScanSampled
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SystemEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SystemEvent_OneofMarshaler, _SystemEvent_OneofUnmarshaler, _SystemEvent_OneofSizer, []interface{}{
		(*SystemEvent_PhotoScanUploaded)(nil),
		(*SystemEvent_PhotoScanSampled)(nil),
	}
}

func _SystemEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SystemEvent)
	// event
	switch x := m.Event.(type) {
	case *SystemEvent_PhotoScanUploaded:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PhotoScanUploaded); err != nil {
			return err
		}
	case *SystemEvent_PhotoScanSampled:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PhotoScanSampled); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SystemEvent.Event has unexpected type %T", x)
	}
	return nil
}

func _SystemEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SystemEvent)
	switch tag {
	case 2: // event.photoScanUploaded
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventPhotoScanUploaded)
		err := b.DecodeMessage(msg)
		m.Event = &SystemEvent_PhotoScanUploaded{msg}
		return true, err
	case 3: // event.photoScanSampled
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventPhotoScanSampled)
		err := b.DecodeMessage(msg)
		m.Event = &SystemEvent_PhotoScanSampled{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SystemEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SystemEvent)
	// event
	switch x := m.Event.(type) {
	case *SystemEvent_PhotoScanUploaded:
		s := proto.Size(x.PhotoScanUploaded)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SystemEvent_PhotoScanSampled:
		s := proto.Size(x.PhotoScanSampled)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EventPhotoScanUploaded struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *EventPhotoScanUploaded) Reset()                    { *m = EventPhotoScanUploaded{} }
func (m *EventPhotoScanUploaded) String() string            { return proto.CompactTextString(m) }
func (*EventPhotoScanUploaded) ProtoMessage()               {}
func (*EventPhotoScanUploaded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventPhotoScanUploaded) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EventPhotoScanSampled struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *EventPhotoScanSampled) Reset()                    { *m = EventPhotoScanSampled{} }
func (m *EventPhotoScanSampled) String() string            { return proto.CompactTextString(m) }
func (*EventPhotoScanSampled) ProtoMessage()               {}
func (*EventPhotoScanSampled) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EventPhotoScanSampled) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PubPhotoScanUploadedRequest struct {
	Context *core.Context `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string        `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *PubPhotoScanUploadedRequest) Reset()                    { *m = PubPhotoScanUploadedRequest{} }
func (m *PubPhotoScanUploadedRequest) String() string            { return proto.CompactTextString(m) }
func (*PubPhotoScanUploadedRequest) ProtoMessage()               {}
func (*PubPhotoScanUploadedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PubPhotoScanUploadedRequest) GetContext() *core.Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PubPhotoScanUploadedRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PubPhotoScanUploadedResponse struct {
	Error *core.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *PubPhotoScanUploadedResponse) Reset()                    { *m = PubPhotoScanUploadedResponse{} }
func (m *PubPhotoScanUploadedResponse) String() string            { return proto.CompactTextString(m) }
func (*PubPhotoScanUploadedResponse) ProtoMessage()               {}
func (*PubPhotoScanUploadedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PubPhotoScanUploadedResponse) GetError() *core.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PubPhotoScanSampledRequest struct {
	Context *core.Context `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string        `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *PubPhotoScanSampledRequest) Reset()                    { *m = PubPhotoScanSampledRequest{} }
func (m *PubPhotoScanSampledRequest) String() string            { return proto.CompactTextString(m) }
func (*PubPhotoScanSampledRequest) ProtoMessage()               {}
func (*PubPhotoScanSampledRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PubPhotoScanSampledRequest) GetContext() *core.Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PubPhotoScanSampledRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PubPhotoScanSampledResponse struct {
	Error *core.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *PubPhotoScanSampledResponse) Reset()                    { *m = PubPhotoScanSampledResponse{} }
func (m *PubPhotoScanSampledResponse) String() string            { return proto.CompactTextString(m) }
func (*PubPhotoScanSampledResponse) ProtoMessage()               {}
func (*PubPhotoScanSampledResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PubPhotoScanSampledResponse) GetError() *core.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*SystemEvent)(nil), "mq.SystemEvent")
	proto.RegisterType((*EventPhotoScanUploaded)(nil), "mq.EventPhotoScanUploaded")
	proto.RegisterType((*EventPhotoScanSampled)(nil), "mq.EventPhotoScanSampled")
	proto.RegisterType((*PubPhotoScanUploadedRequest)(nil), "mq.PubPhotoScanUploadedRequest")
	proto.RegisterType((*PubPhotoScanUploadedResponse)(nil), "mq.PubPhotoScanUploadedResponse")
	proto.RegisterType((*PubPhotoScanSampledRequest)(nil), "mq.PubPhotoScanSampledRequest")
	proto.RegisterType((*PubPhotoScanSampledResponse)(nil), "mq.PubPhotoScanSampledResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for InternalMQService service

type InternalMQServiceClient interface {
	// Publish an event indicating that the specified scan image was successfully uploaded.
	PubPhotoScanUploaded(ctx context.Context, in *PubPhotoScanUploadedRequest, opts ...grpc.CallOption) (*PubPhotoScanUploadedResponse, error)
	// Publish an event indicating that the specified scan image was successfully sampled.
	PubPhotoScanSampled(ctx context.Context, in *PubPhotoScanSampledRequest, opts ...grpc.CallOption) (*PubPhotoScanSampledResponse, error)
}

type internalMQServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalMQServiceClient(cc *grpc.ClientConn) InternalMQServiceClient {
	return &internalMQServiceClient{cc}
}

func (c *internalMQServiceClient) PubPhotoScanUploaded(ctx context.Context, in *PubPhotoScanUploadedRequest, opts ...grpc.CallOption) (*PubPhotoScanUploadedResponse, error) {
	out := new(PubPhotoScanUploadedResponse)
	err := grpc.Invoke(ctx, "/mq.InternalMQService/PubPhotoScanUploaded", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalMQServiceClient) PubPhotoScanSampled(ctx context.Context, in *PubPhotoScanSampledRequest, opts ...grpc.CallOption) (*PubPhotoScanSampledResponse, error) {
	out := new(PubPhotoScanSampledResponse)
	err := grpc.Invoke(ctx, "/mq.InternalMQService/PubPhotoScanSampled", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InternalMQService service

type InternalMQServiceServer interface {
	// Publish an event indicating that the specified scan image was successfully uploaded.
	PubPhotoScanUploaded(context.Context, *PubPhotoScanUploadedRequest) (*PubPhotoScanUploadedResponse, error)
	// Publish an event indicating that the specified scan image was successfully sampled.
	PubPhotoScanSampled(context.Context, *PubPhotoScanSampledRequest) (*PubPhotoScanSampledResponse, error)
}

func RegisterInternalMQServiceServer(s *grpc.Server, srv InternalMQServiceServer) {
	s.RegisterService(&_InternalMQService_serviceDesc, srv)
}

func _InternalMQService_PubPhotoScanUploaded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubPhotoScanUploadedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMQServiceServer).PubPhotoScanUploaded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mq.InternalMQService/PubPhotoScanUploaded",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMQServiceServer).PubPhotoScanUploaded(ctx, req.(*PubPhotoScanUploadedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalMQService_PubPhotoScanSampled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubPhotoScanSampledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMQServiceServer).PubPhotoScanSampled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mq.InternalMQService/PubPhotoScanSampled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMQServiceServer).PubPhotoScanSampled(ctx, req.(*PubPhotoScanSampledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalMQService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mq.InternalMQService",
	HandlerType: (*InternalMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PubPhotoScanUploaded",
			Handler:    _InternalMQService_PubPhotoScanUploaded_Handler,
		},
		{
			MethodName: "PubPhotoScanSampled",
			Handler:    _InternalMQService_PubPhotoScanSampled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mq-service.proto",
}

func init() { proto.RegisterFile("mq-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x69, 0x0d, 0x12, 0x2f, 0xd1, 0xc0, 0xf8, 0x13, 0xac, 0x46, 0xb0, 0x1b, 0xd8, 0xd8,
	0x05, 0xbe, 0x80, 0x3f, 0x21, 0xa2, 0x89, 0x09, 0x4e, 0x03, 0x89, 0xcb, 0xd2, 0xde, 0x44, 0x12,
	0x3a, 0xd3, 0x4e, 0x07, 0xa2, 0x2f, 0xe8, 0x13, 0xf8, 0x40, 0xa6, 0x33, 0xb5, 0x11, 0x5a, 0x8c,
	0xc6, 0x65, 0xef, 0x3d, 0xe7, 0xcb, 0x39, 0xb7, 0x2d, 0x34, 0xc2, 0xf8, 0x22, 0x41, 0xb1, 0x9c,
	0xf9, 0xe8, 0x44, 0x82, 0x4b, 0x4e, 0xcc, 0x30, 0xb6, 0xc0, 0xe7, 0x22, 0x7b, 0xb6, 0x3f, 0x0c,
	0xa8, 0xbb, 0x6f, 0x89, 0xc4, 0x70, 0xb0, 0x44, 0x26, 0x49, 0x17, 0x6a, 0x3e, 0x67, 0x12, 0x5f,
	0x65, 0xcb, 0xe8, 0x18, 0xbd, 0x7a, 0x7f, 0xd7, 0x51, 0xea, 0x5b, 0x3d, 0xa4, 0x5f, 0x5b, 0xf2,
	0x00, 0xcd, 0xe8, 0x85, 0x4b, 0xee, 0xfa, 0x1e, 0x1b, 0x47, 0x73, 0xee, 0x05, 0x18, 0xb4, 0x4c,
	0x65, 0xb1, 0x9c, 0x30, 0x76, 0x14, 0x6e, 0xb4, 0xae, 0x18, 0x56, 0x68, 0xd1, 0x46, 0xee, 0xa0,
	0x91, 0x0f, 0x5d, 0x2f, 0x8c, 0xe6, 0x18, 0xb4, 0xb6, 0x14, 0xea, 0xb8, 0x88, 0xca, 0x04, 0xc3,
	0x0a, 0x2d, 0x98, 0x6e, 0x6a, 0x50, 0xc5, 0x54, 0x6c, 0xf7, 0xe0, 0xa8, 0x3c, 0x00, 0xd9, 0x03,
	0x73, 0x16, 0xa8, 0x6e, 0x3b, 0xd4, 0x9c, 0x05, 0x76, 0x17, 0x0e, 0x4b, 0xf9, 0x05, 0xe1, 0x04,
	0x4e, 0x46, 0x8b, 0x69, 0x01, 0x48, 0x31, 0x5e, 0x60, 0xf2, 0x87, 0xc3, 0x69, 0xae, 0x99, 0x73,
	0xaf, 0xe1, 0xb4, 0x9c, 0x9b, 0x44, 0x9c, 0x25, 0x48, 0xce, 0xa1, 0x8a, 0x42, 0x70, 0x91, 0x61,
	0xeb, 0x1a, 0x3b, 0x48, 0x47, 0x54, 0x6f, 0xec, 0x31, 0x58, 0xdf, 0x11, 0x59, 0x83, 0x7f, 0x27,
	0xbb, 0x5a, 0x6d, 0x9c, 0x63, 0x7f, 0x1d, 0xac, 0xff, 0x6e, 0x40, 0xf3, 0x9e, 0x49, 0x14, 0xcc,
	0x9b, 0x3f, 0x3e, 0xb9, 0xfa, 0x4b, 0x24, 0xcf, 0x70, 0x50, 0xd6, 0x98, 0xb4, 0xd3, 0x97, 0xfd,
	0xc3, 0x8d, 0xad, 0xce, 0x66, 0x41, 0x96, 0x69, 0x02, 0xfb, 0x25, 0x91, 0xc9, 0xd9, 0xba, 0x71,
	0xf5, 0x44, 0x56, 0x7b, 0xe3, 0x5e, 0x73, 0xa7, 0xdb, 0xea, 0x6f, 0xb9, 0xfc, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0x91, 0x2b, 0xf6, 0x7b, 0x51, 0x03, 0x00, 0x00,
}
