// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

/*
Package core is a generated protocol buffer package.

It is generated from these files:
	core.proto

It has these top-level messages:
	Auth
	Context
	Error
	PageRequest
	PageResponse
*/
package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / A structure holding all data needed for establishing request authentication.
type Auth struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// / A structure holding all metadata needed for request metadata, tracing and the like.
type Context struct {
	Requestid string `protobuf:"bytes,1,opt,name=requestid" json:"requestid,omitempty"`
}

func (m *Context) Reset()                    { *m = Context{} }
func (m *Context) String() string            { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()               {}
func (*Context) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Context) GetRequestid() string {
	if m != nil {
		return m.Requestid
	}
	return ""
}

// / Error is a structured description of any error which has occurred during an RPC request.
// /
// / This should be used as the first field of any RPC response message. Its presence represents an
// / error which has occurred during the RPC execution.
// /
// / Any information given to an instance of this object must be presentable to a user. Ensure the
// / data has been sanitized and is ready for user consumption.
type Error struct {
	Message string            `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Status  uint32            `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Code    string            `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	Meta    map[string]string `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// / A structure describing a request for a page of data.
type PageRequest struct {
	Page uint64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *PageRequest) Reset()                    { *m = PageRequest{} }
func (m *PageRequest) String() string            { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()               {}
func (*PageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PageRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// / A structure describing a response of paged data.
type PageResponse struct {
	Page   uint64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size   uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Total  uint64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	IsLast bool   `protobuf:"varint,4,opt,name=isLast" json:"isLast,omitempty"`
}

func (m *PageResponse) Reset()                    { *m = PageResponse{} }
func (m *PageResponse) String() string            { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()               {}
func (*PageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PageResponse) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PageResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageResponse) GetIsLast() bool {
	if m != nil {
		return m.IsLast
	}
	return false
}

func init() {
	proto.RegisterType((*Auth)(nil), "core.Auth")
	proto.RegisterType((*Context)(nil), "core.Context")
	proto.RegisterType((*Error)(nil), "core.Error")
	proto.RegisterType((*PageRequest)(nil), "core.PageRequest")
	proto.RegisterType((*PageResponse)(nil), "core.PageResponse")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x49, 0x37, 0x6d, 0xdd, 0xa9, 0x82, 0x04, 0x95, 0x20, 0x3d, 0x2c, 0x7b, 0x71, 0xbd,
	0xec, 0x41, 0x11, 0xc5, 0x9b, 0x48, 0x6f, 0x0a, 0x92, 0x6f, 0x10, 0xbb, 0x43, 0x5d, 0xda, 0x6e,
	0xd6, 0x64, 0x56, 0xac, 0xdf, 0xca, 0x6f, 0x28, 0xf9, 0x53, 0xbd, 0x7a, 0x7b, 0xbf, 0xe1, 0x0d,
	0xf3, 0x5e, 0x02, 0xb0, 0x34, 0x16, 0xeb, 0xde, 0x1a, 0x32, 0x82, 0x7b, 0x5d, 0xce, 0x81, 0x3f,
	0x0c, 0xf4, 0x26, 0x4e, 0x60, 0x4c, 0x66, 0x8d, 0x9d, 0x64, 0x05, 0xab, 0x72, 0x15, 0xa1, 0xbc,
	0x80, 0xe9, 0xa3, 0xe9, 0x08, 0x3f, 0x49, 0xcc, 0x21, 0xb7, 0xf8, 0x3e, 0xa0, 0xa3, 0xb6, 0x49,
	0xa6, 0xbf, 0x41, 0xf9, 0xcd, 0x60, 0xbc, 0xb0, 0xd6, 0x58, 0x21, 0x61, 0xba, 0x45, 0xe7, 0xf4,
	0x0a, 0x93, 0x6b, 0x8f, 0xe2, 0x0c, 0x26, 0x8e, 0x34, 0x0d, 0x4e, 0x8e, 0x0a, 0x56, 0x1d, 0xa9,
	0x44, 0x42, 0x00, 0x5f, 0x9a, 0x06, 0x65, 0x16, 0xec, 0x41, 0x8b, 0x4b, 0xe0, 0x5b, 0x24, 0x2d,
	0x79, 0x91, 0x55, 0xb3, 0xab, 0xd3, 0x3a, 0xe4, 0x0e, 0x07, 0xea, 0x67, 0x24, 0xbd, 0xe8, 0xc8,
	0xee, 0x54, 0xb0, 0x9c, 0xdf, 0x42, 0xfe, 0x3b, 0x12, 0xc7, 0x90, 0xad, 0x71, 0x97, 0x2e, 0x7b,
	0xe9, 0x8b, 0x7d, 0xe8, 0xcd, 0x80, 0xe1, 0x68, 0xae, 0x22, 0xdc, 0x8f, 0xee, 0x58, 0x79, 0x03,
	0xb3, 0x17, 0xbd, 0x42, 0x15, 0x4b, 0xf8, 0x18, 0xfd, 0x3e, 0x35, 0x57, 0x41, 0xfb, 0x99, 0x6b,
	0xbf, 0xe2, 0x2e, 0x57, 0x41, 0x97, 0x0d, 0x1c, 0xc6, 0x35, 0xd7, 0x9b, 0xce, 0xe1, 0x7f, 0xf7,
	0xe2, 0x0b, 0x93, 0xde, 0x84, 0x9e, 0x5c, 0x45, 0xf0, 0x8f, 0xd2, 0xba, 0x27, 0xed, 0x48, 0xf2,
	0x82, 0x55, 0x07, 0x2a, 0xd1, 0xeb, 0x24, 0x7c, 0xd2, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0x50, 0x7a, 0xae, 0xb2, 0x01, 0x00, 0x00,
}
